version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout

      - attach_workspace:
          at: ~/eslint-config-gsc

      - restore_cache:
          keys:
            - eslint-config-gsc-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - eslint-config-gsc-v1-{{ .Branch }}-
            - eslint-config-gsc-v1-

      - run:
          name: Install Dependecies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: eslint-config-gsc-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          pwd: eslint-config-gsc
          name: Run Tests
          command: yarn lint
